# This compose file should be used only for development environment

services:
  backend:
    command: [ "--reload" ]

  redis:
    restart: "no"
    ports:
      - 6379
  
  postgres:
    restart: "no"
    ports:
      - 5432
