# This compose file should be used only for development environment

services:
  backend:
    build:
      target: development
    volumes:
      - ./backend/app:/backend/app

  redis:
    restart: "no"
    ports:
      - 6379
  
  postgres:
    restart: "no"
    ports:
      - 5432
