
USER_PASSWORD_KEY_LENGTH = 64
USER_PASSWORD_SALT_LENGTH = 64
USER_NAME_LENGTH = 50
USER_LOCATION_LENGTH = 50
USER_INTEREST_LENGTH = 30
USER_BRIEF_DESCRIPTION_LENGTH = 120
USER_DESCRIPTION_LENGTH = 500
